# Generated by Django 3.0.5 on 2020-04-13 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_name', models.CharField(max_length=250)),
                ('round_number', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=250)),
                ('person_1_name', models.CharField(max_length=100)),
                ('person_2_name', models.CharField(blank=True, max_length=100)),
                ('person_3_name', models.CharField(blank=True, max_length=100)),
                ('person_4_name', models.CharField(blank=True, max_length=100)),
                ('person_5_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.CharField(blank=True, max_length=500)),
                ('answer_1', models.CharField(max_length=100)),
                ('question_2', models.CharField(blank=True, max_length=500)),
                ('answer_2', models.CharField(max_length=100)),
                ('question_3', models.CharField(blank=True, max_length=500)),
                ('answer_3', models.CharField(max_length=100)),
                ('question_4', models.CharField(blank=True, max_length=500)),
                ('answer_4', models.CharField(max_length=100)),
                ('question_5', models.CharField(blank=True, max_length=500)),
                ('answer_5', models.CharField(max_length=100)),
                ('this_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answers.Round')),
                ('this_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answers.Team')),
            ],
        ),
    ]
