# Generated by Django 3.0.5 on 2020-04-13 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted', models.DateTimeField()),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=20)),
                ('question_1', models.CharField(blank=True, max_length=500)),
                ('answer_1', models.CharField(max_length=100)),
                ('question_2', models.CharField(blank=True, max_length=500)),
                ('answer_2', models.CharField(max_length=100)),
                ('question_3', models.CharField(blank=True, max_length=500)),
                ('answer_3', models.CharField(max_length=100)),
                ('question_4', models.CharField(blank=True, max_length=500)),
                ('answer_4', models.CharField(max_length=100)),
                ('question_5', models.CharField(blank=True, max_length=500)),
                ('answer_5', models.CharField(max_length=100)),
                ('this_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answers.Round')),
                ('this_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answers.Team')),
            ],
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
    ]
