# Generated by Django 3.0.5 on 2020-04-13 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0003_auto_20200414_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='answer_1',
        ),
        migrations.RemoveField(
            model_name='result',
            name='answer_2',
        ),
        migrations.RemoveField(
            model_name='result',
            name='answer_3',
        ),
        migrations.RemoveField(
            model_name='result',
            name='answer_4',
        ),
        migrations.RemoveField(
            model_name='result',
            name='answer_5',
        ),
        migrations.AddField(
            model_name='round',
            name='answer_1',
            field=models.CharField(default='correct', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='round',
            name='answer_2',
            field=models.CharField(default='correct', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='round',
            name='answer_3',
            field=models.CharField(default='correct', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='round',
            name='answer_4',
            field=models.CharField(default='correct', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='round',
            name='answer_5',
            field=models.CharField(default='correct', max_length=100),
            preserve_default=False,
        ),
    ]
