# Generated by Django 3.0.5 on 2020-04-13 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0004_auto_20200414_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='question_10',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='result',
            name='question_11',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='result',
            name='question_12',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='result',
            name='question_13',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='result',
            name='question_14',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='result',
            name='question_15',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='result',
            name='question_16',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='result',
            name='question_17',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='result',
            name='question_18',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='result',
            name='question_19',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='result',
            name='question_20',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='result',
            name='question_6',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='result',
            name='question_7',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='result',
            name='question_8',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='result',
            name='question_9',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='round',
            name='answer_10',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='round',
            name='answer_11',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='round',
            name='answer_12',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='round',
            name='answer_13',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='round',
            name='answer_14',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='round',
            name='answer_15',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='round',
            name='answer_16',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='round',
            name='answer_17',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='round',
            name='answer_18',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='round',
            name='answer_19',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='round',
            name='answer_20',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='round',
            name='answer_6',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='round',
            name='answer_7',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='round',
            name='answer_8',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='round',
            name='answer_9',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='round',
            name='score_1',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='round',
            name='score_10',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='round',
            name='score_11',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='round',
            name='score_12',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='round',
            name='score_13',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='round',
            name='score_14',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='round',
            name='score_15',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='round',
            name='score_16',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='round',
            name='score_17',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='round',
            name='score_18',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='round',
            name='score_19',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='round',
            name='score_2',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='round',
            name='score_20',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='round',
            name='score_3',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='round',
            name='score_4',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='round',
            name='score_5',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='round',
            name='score_6',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='round',
            name='score_7',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='round',
            name='score_8',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='round',
            name='score_9',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='result',
            name='score',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='round',
            name='answer_1',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='round',
            name='answer_2',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='round',
            name='answer_3',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='round',
            name='answer_4',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='round',
            name='answer_5',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='round',
            name='round_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(max_length=500),
        ),
    ]
