# Generated by Django 3.0.5 on 2020-04-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0006_result_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='round',
            name='score_1',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='round',
            name='score_10',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='round',
            name='score_11',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='round',
            name='score_12',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='round',
            name='score_13',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='round',
            name='score_14',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='round',
            name='score_15',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='round',
            name='score_16',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='round',
            name='score_17',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='round',
            name='score_18',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='round',
            name='score_19',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='round',
            name='score_2',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='round',
            name='score_20',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='round',
            name='score_3',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='round',
            name='score_4',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='round',
            name='score_5',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='round',
            name='score_6',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='round',
            name='score_7',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='round',
            name='score_8',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='round',
            name='score_9',
            field=models.FloatField(default=1.0),
        ),
    ]
