# Generated by Django 3.0.5 on 2020-04-15 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0008_auto_20200414_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_email',
            field=models.EmailField(default='darren.mansell@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='result',
            name='log',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
