# Generated by Django 3.0.5 on 2020-04-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0009_auto_20200415_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='bingo_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_email',
            field=models.EmailField(max_length=254),
        ),
    ]
