from django.db import models

# Create your models here.
class Round(models.Model):
    round_name = models.CharField(max_length=500)
    round_number = models.IntegerField(default=1)
    answer_1 = models.CharField(max_length=500, blank=True)
    score_1 = models.DecimalField(max_digits=10, decimal_places=1, default=1.0)
    answer_2 = models.CharField(max_length=500, blank=True)
    score_2 = models.DecimalField(max_digits=10, decimal_places=1, default=1.0)
    answer_3 = models.CharField(max_length=500, blank=True)
    score_3 = models.DecimalField(max_digits=10, decimal_places=1, default=1.0)
    answer_4 = models.CharField(max_length=500, blank=True)
    score_4 = models.DecimalField(max_digits=10, decimal_places=1, default=1.0)  
    answer_5 = models.CharField(max_length=500, blank=True)
    score_5 = models.DecimalField(max_digits=10, decimal_places=1, default=1.0)
    answer_6 = models.CharField(max_length=500, blank=True)
    score_6 = models.DecimalField(max_digits=10, decimal_places=1, default=1.0)
    answer_7 = models.CharField(max_length=500, blank=True)
    score_7 = models.DecimalField(max_digits=10, decimal_places=1, default=1.0)
    answer_8 = models.CharField(max_length=500, blank=True)
    score_8 = models.DecimalField(max_digits=10, decimal_places=1, default=1.0)  
    answer_9 = models.CharField(max_length=500, blank=True)
    score_9 = models.DecimalField(max_digits=10, decimal_places=1, default=1.0)
    answer_10 = models.CharField(max_length=500, blank=True)
    score_10 = models.DecimalField(max_digits=10, decimal_places=1, default=1.0) 
    answer_11 = models.CharField(max_length=500, blank=True)
    score_11 = models.DecimalField(max_digits=10, decimal_places=1, default=1.0)
    answer_12 = models.CharField(max_length=500, blank=True)
    score_12 = models.DecimalField(max_digits=10, decimal_places=1, default=1.0) 
    answer_13 = models.CharField(max_length=500, blank=True)
    score_13 = models.DecimalField(max_digits=10, decimal_places=1, default=1.0)
    answer_14 = models.CharField(max_length=500, blank=True)
    score_14 = models.DecimalField(max_digits=10, decimal_places=1, default=1.0)
    answer_15 = models.CharField(max_length=500, blank=True)
    score_15 = models.DecimalField(max_digits=10, decimal_places=1, default=1.0)
    answer_16 = models.CharField(max_length=500, blank=True)
    score_16 = models.DecimalField(max_digits=10, decimal_places=1, default=1.0)
    answer_17 = models.CharField(max_length=500, blank=True)
    score_17 = models.DecimalField(max_digits=10, decimal_places=1, default=1.0)
    answer_18 = models.CharField(max_length=500, blank=True)
    score_18 = models.DecimalField(max_digits=10, decimal_places=1, default=1.0) 
    answer_19 = models.CharField(max_length=500, blank=True)
    score_19 = models.DecimalField(max_digits=10, decimal_places=1, default=1.0)
    answer_20 = models.CharField(max_length=500, blank=True)
    score_20 = models.DecimalField(max_digits=10, decimal_places=1, default=1.0)                                                         
    def __str__(self):
        return self.round_name

class Team(models.Model):
    team_name = models.CharField(max_length=500)
    person_1_name = models.CharField(max_length=100)
    person_2_name = models.CharField(max_length=100, blank=True)
    person_3_name = models.CharField(max_length=100, blank=True)
    person_4_name = models.CharField(max_length=100, blank=True)
    person_5_name = models.CharField(max_length=100, blank=True)
    def __str__(self):
        return self.team_name

class Result(models.Model):
    submitted = models.DateTimeField(auto_now=True)
    this_round = models.ForeignKey(Round, on_delete=models.CASCADE)
    this_team = models.ForeignKey(Team, on_delete=models.CASCADE)
    score = models.DecimalField(max_digits=10, decimal_places=1, default=0.0)
    question_1 = models.CharField(max_length=500, blank=True)
    question_2 = models.CharField(max_length=500, blank=True)
    question_3 = models.CharField(max_length=500, blank=True)
    question_4 = models.CharField(max_length=500, blank=True)
    question_5 = models.CharField(max_length=500, blank=True)
    question_6 = models.CharField(max_length=500, blank=True)
    question_7 = models.CharField(max_length=500, blank=True)
    question_8 = models.CharField(max_length=500, blank=True)
    question_9 = models.CharField(max_length=500, blank=True)
    question_10 = models.CharField(max_length=500, blank=True)
    question_11 = models.CharField(max_length=500, blank=True)
    question_12 = models.CharField(max_length=500, blank=True)
    question_13 = models.CharField(max_length=500, blank=True)
    question_14 = models.CharField(max_length=500, blank=True)
    question_15 = models.CharField(max_length=500, blank=True)
    question_16 = models.CharField(max_length=500, blank=True)
    question_17 = models.CharField(max_length=500, blank=True)
    question_18 = models.CharField(max_length=500, blank=True)
    question_19 = models.CharField(max_length=500, blank=True)
    question_20 = models.CharField(max_length=500, blank=True)
    log = models.CharField(max_length=2000, blank=True)            
    def __str__(self):
        return str(self.submitted) + ' ' + str(self.this_round) + ' ' + str(self.this_team)